# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(blank=True, verbose_name='修改时间'),
        ),
    ]
